name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifacts-name: 
        description: name of artifact files
        required: false
        default: dist
        type: string
    # secrets:
    #   some-secret:
    #     description: secret of secret
    #     required: false
    outputs:
      step-result:
        description: output of step-result
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code  
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifacts-name }}
      - name: List files
        run: ls
      - name: Output
        run: echo 'deploying...'
      - name: Set result Output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT